name: tono_music
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_js: ^0.8.5
  encrypt: ^5.0.3
  music_sdk:
    git:
      url: https://github.com/enten0103/music_sdk
  get: ^4.7.2
  file_picker: ^10.3.3
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  window_manager: ^0.5.1
  just_audio: ^0.10.5
  audio_session: ^0.2.2
  just_audio_windows: 
    git:
      url: https://github.com/hig-dev/just_audio_windows
      path: just_audio_windows
  logger: ^1.3.0
  awesome_notifications_core: ^0.10.1
  awesome_notifications: ^0.10.1
  palette_generator: ^0.3.3+7
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: OppoSans
      fonts:
        - asset: assets/OPPO Sans 4.0.ttf