name: tono_music
description: "TonoMusic Application Based on Flutter"
publish_to: 'none' 

version: 1.0.2+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_displaymode:
  cupertino_icons: ^1.0.8
  flutter_js: ^0.8.5
  encrypt: ^5.0.3
  music_sdk:
    git:
      url: https://github.com/enten0103/music_sdk
  get: ^4.7.2
  file_picker: ^10.3.3
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  window_manager: ^0.5.1
  audio_session: ^0.2.2
  logger: ^1.3.0
  palette_generator: ^0.3.3+7
  http: ^1.5.0
  smtc_windows: ^1.1.0
  media_kit: ^1.2.1
  media_kit_libs_audio: ^1.0.7
  tray_manager: ^0.5.1
  system_fonts: ^1.0.1
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon.ico
